## Load Data

In [31]:
from datasets import load_dataset
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Loading Data

In [32]:

# Load the full dataset
dataset = load_dataset("divarofficial/real_estate_ads")

# Get dataset statistics
print(f"Dataset size: {len(dataset['train'])} rows")
print(f"Features: {dataset['train'].features}")

Dataset size: 1000000 rows
Features: {'cat2_slug': Value('string'), 'cat3_slug': Value('string'), 'city_slug': Value('string'), 'neighborhood_slug': Value('string'), 'created_at_month': Value('string'), 'user_type': Value('string'), 'description': Value('string'), 'title': Value('string'), 'rent_mode': Value('string'), 'rent_value': Value('float64'), 'rent_to_single': Value('float64'), 'rent_type': Value('string'), 'price_mode': Value('string'), 'price_value': Value('float64'), 'credit_mode': Value('string'), 'credit_value': Value('float64'), 'rent_credit_transform': Value('bool'), 'transformable_price': Value('bool'), 'transformable_credit': Value('float64'), 'transformed_credit': Value('float64'), 'transformable_rent': Value('float64'), 'transformed_rent': Value('float64'), 'land_size': Value('float64'), 'building_size': Value('float64'), 'deed_type': Value('string'), 'has_business_deed': Value('bool'), 'floor': Value('string'), 'rooms_count': Value('string'), 'total_floors_count': Value('string'), 'unit_per_floor': Value('string'), 'has_balcony': Value('string'), 'has_elevator': Value('bool'), 'has_warehouse': Value('bool'), 'has_parking': Value('bool'), 'construction_year': Value('string'), 'is_rebuilt': Value('bool'), 'has_water': Value('bool'), 'has_warm_water_provider': Value('string'), 'has_electricity': Value('bool'), 'has_gas': Value('bool'), 'has_heating_system': Value('string'), 'has_cooling_system': Value('string'), 'has_restroom': Value('string'), 'has_security_guard': Value('bool'), 'has_barbecue': Value('bool'), 'building_direction': Value('string'), 'has_pool': Value('bool'), 'has_jacuzzi': Value('bool'), 'has_sauna': Value('bool'), 'floor_material': Value('string'), 'property_type': Value('string'), 'regular_person_capacity': Value('float64'), 'extra_person_capacity': Value('string'), 'cost_per_extra_person': Value('float64'), 'rent_price_on_regular_days': Value('float64'), 'rent_price_on_special_days': Value('float64'), 'rent_price_at_weekends': Value('float64'), 'location_latitude': Value('float64'), 'location_longitude': Value('float64'), 'location_radius': Value('float64')}

### Convert to Data Frame

In [33]:
df = dataset["train"].to_pandas()
df.head(5)

,cat2_slug,cat3_slug,city_slug,neighborhood_slug,created_at_month,user_type,description,title,rent_mode,rent_value,...,property_type,regular_person_capacity,extra_person_capacity,cost_per_extra_person,rent_price_on_regular_days,rent_price_on_special_days,rent_price_at_weekends,location_latitude,location_longitude,location_radius
0,temporary-rent,villa,karaj,mehrshahr,2024-08-01 00:00:00,مشاور املاک,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,None,NaN,...,None,4.0,6,350000.0,1500000.0,3.500000e+09,3500000.0,35.811684,50.936600,500.0
1,residential-sell,apartment-sell,tehran,gholhak,2024-05-01 00:00:00,مشاور املاک,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,۶۰ متر قلهک فول امکانات,None,NaN,...,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,500.0
2,residential-rent,apartment-rent,tehran,tohid,2024-10-01 00:00:00,None,تخلیه پایان ماه,آپارتمان ۳ خوابه ۱۳۲ متر,مقطوع,26000000.0,...,None,NaN,None,NaN,NaN,NaN,NaN,35.703865,51.373459,NaN
3,commercial-rent,office-rent,tehran,elahiyeh,2024-06-01 00:00:00,None,فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...,فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری,مقطوع,95000000.0,...,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,residential-sell,apartment-sell,mashhad,emamreza,2024-05-01 00:00:00,مشاور املاک,هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...,۱۱۵ متری/شمالی رو به آفتاب/اکبری,None,NaN,...,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df.info()
df.columns
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 60 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   cat2_slug                   1000000 non-null  object
 1   cat3_slug                   999999 non-null   object
 2   city_slug                   999998 non-null   object
 3   neighborhood_slug           437139 non-null   object
 4   created_at_month            1000000 non-null  object
 5   user_type                   288882 non-null   object
 6   description                 1000000 non-null  object
 7   title                       999946 non-null   object
 8   rent_mode                   352994 non-null   object
 9   rent_value                  351322 non-null   float64
 10  rent_to_single              19 non-null       float64
 11  rent_type                   103961 non-null   object
 12  price_mode                  573606 non-null   object
 13  price_value                 568346 non-null   float64
 14  credit_mode                 352994 non-null   object
 15  credit_value                352095 non-null   float64
 16  rent_credit_transform       352985 non-null   object
 17  transformable_price         352894 non-null   object
 18  transformable_credit        352085 non-null   float64
 19  transformed_credit          72409 non-null    float64
 20  transformable_rent          351248 non-null   float64
 21  transformed_rent            72409 non-null    float64
 22  land_size                   186396 non-null   float64
 23  building_size               980394 non-null   float64
 24  deed_type                   253458 non-null   object
 25  has_business_deed           34679 non-null    object
 26  floor                       541748 non-null   object
 27  rooms_count                 845899 non-null   object
 28  total_floors_count          304352 non-null   object
 29  unit_per_floor              302283 non-null   object
 30  has_balcony                 506411 non-null   object
 31  has_elevator                541749 non-null   object
 32  has_warehouse               728155 non-null   object
 33  has_parking                 728156 non-null   object
 34  construction_year           815828 non-null   object
 35  is_rebuilt                  529470 non-null   object
 36  has_water                   33444 non-null    object
 37  has_warm_water_provider     379500 non-null   object
 38  has_electricity             33445 non-null    object
 39  has_gas                     33430 non-null    object
 40  has_heating_system          368969 non-null   object
 41  has_cooling_system          350619 non-null   object
 42  has_restroom                406913 non-null   object
 43  has_security_guard          31312 non-null    object
 44  has_barbecue                31198 non-null    object
 45  building_direction          323923 non-null   object
 46  has_pool                    29390 non-null    object
 47  has_jacuzzi                 28728 non-null    object
 48  has_sauna                   28479 non-null    object
 49  floor_material              405984 non-null   object
 50  property_type               27057 non-null    object
 51  regular_person_capacity     29870 non-null    float64
 52  extra_person_capacity       24009 non-null    object
 53  cost_per_extra_person       10241 non-null    float64
 54  rent_price_on_regular_days  18068 non-null    float64
 55  rent_price_on_special_days  10463 non-null    float64
 56  rent_price_at_weekends      13551 non-null    float64
 57  location_latitude           655608 non-null   float64
 58  location_longitude          655608 non-null   float64
 59  location_radius             339699 non-null   float64
dtypes: float64(18), object(42)
memory usage: 457.8+ MB

,rent_value,rent_to_single,price_value,credit_value,transformable_credit,transformed_credit,transformable_rent,transformed_rent,land_size,building_size,regular_person_capacity,cost_per_extra_person,rent_price_on_regular_days,rent_price_on_special_days,rent_price_at_weekends,location_latitude,location_longitude,location_radius
count,3.513220e+05,19.000000,5.683460e+05,3.520950e+05,3.520850e+05,7.240900e+04,3.512480e+05,7.240900e+04,1.863960e+05,9.803940e+05,29870.000000,1.024100e+04,1.806800e+04,1.046300e+04,1.355100e+04,655608.000000,655608.000000,339699.000000
mean,4.102299e+10,0.947368,1.736537e+10,4.872084e+10,4.872222e+10,8.557025e+09,4.103164e+10,1.619934e+07,4.165480e+03,4.440648e+03,6.557650,1.209785e+10,1.389016e+11,2.355548e+10,3.156551e+10,34.982108,51.629743,465.149147
std,3.807534e+12,0.229416,5.878739e+11,4.341346e+12,4.341407e+12,2.064576e+12,3.807935e+12,5.217890e+07,1.218927e+05,1.367118e+05,7.698655,1.103482e+12,7.042335e+12,1.542049e+12,2.434942e+12,2.379169,3.160920,125.896250
min,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,23.626478,40.162369,0.000000
25%,1.111110e+05,1.000000,1.400000e+09,1.000000e+08,1.000000e+08,2.000000e+08,1.111110e+05,1.000000e+06,1.100000e+02,7.500000e+01,3.000000,5.000000e+04,4.000000e+05,6.000000e+05,5.500000e+05,34.553551,50.677175,500.000000
50%,5.000000e+06,1.000000,2.840000e+09,2.500000e+08,2.500000e+08,4.000000e+08,5.000000e+06,6.000000e+06,1.950000e+02,1.030000e+02,4.000000,1.000000e+05,8.000000e+05,1.200000e+06,1.100000e+06,35.723312,51.345791,500.000000
75%,1.200000e+07,1.000000,5.900000e+09,5.000000e+08,5.000000e+08,8.500000e+08,1.200000e+07,1.500000e+07,2.800000e+02,1.650000e+02,7.000000,2.000000e+05,1.600000e+06,2.500000e+06,2.500000e+06,36.307013,51.805291,500.000000
max,1.000000e+15,1.000000,1.000000e+14,1.000000e+15,1.000000e+15,5.555556e+14,1.000000e+15,3.000000e+09,1.000000e+07,1.000000e+07,50.000000,1.111111e+14,5.006007e+14,1.111111e+14,2.002503e+14,40.358055,74.511620,500.000000

## Cleaning Data

In [35]:
mapping = {
    "null" : np.nan,
    "بدون اتاق":0,
    "یک": 1,
    "دو": 2,
    "سه": 3,
    "چهار": 4,
    "پنج یا بیشتر" : 5
}

df["rooms_count"] = df["rooms_count"].replace(mapping)
# print(df["rooms_count"].unique())



# ------------------------------------------------------------------------------


construction_year_mapping = {
    "null": np.nan,
    None: np.nan,
    
    "قبل از ۱۳۷۰": 1370,
    "۱۳۷۱": 1371,
    "۱۳۷۲": 1372,
    "۱۳۷۳": 1373,
    "۱۳۷۴": 1374,
    "۱۳۷۵": 1375,
    "۱۳۷۶": 1376,
    "۱۳۷۷": 1377,
    "۱۳۷۸": 1378,
    "۱۳۷۹": 1379,
    "۱۳۸۰": 1380,
    "۱۳۸۱": 1381,
    "۱۳۸۲": 1382,
    "۱۳۸۳": 1383,
    "۱۳۸۴": 1384,
    "۱۳۸۵": 1385,
    "۱۳۸۶": 1386,
    "۱۳۸۷": 1387,
    "۱۳۸۸": 1388,
    "۱۳۸۹": 1389,
    "۱۳۹۰": 1390,
    "۱۳۹۱": 1391,
    "۱۳۹۲": 1392,
    "۱۳۹۳": 1393,
    "۱۳۹۴": 1394,
    "۱۳۹۵": 1395,
    "۱۳۹۶": 1396,
    "۱۳۹۷": 1397,
    "۱۳۹۸": 1398,
    "۱۳۹۹": 1399,
    "۱۴۰۰": 1400,
    "۱۴۰۱": 1401,
    "۱۴۰۲": 1402,
    "۱۴۰۳": 1403,
}

df["construction_year"] = df["construction_year"].replace(construction_year_mapping)
# print(df["construction_year"].unique())


# Change created_at_month type to datetime
df["created_at_month"] = pd.to_datetime(
    df["created_at_month"].astype("string"),
    errors="coerce"
)

# print(df["created_at_month"].dtype)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_13316\613891193.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["rooms_count"] = df["rooms_count"].replace(mapping)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_13316\613891193.py:59: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["construction_year"] = df["construction_year"].replace(construction_year_mapping)

In [36]:
df["floor"]=(
    df["floor"].replace({"30+":"30"}).astype("Int64")
)

df["total_floors_count"]=(
    df["total_floors_count"].replace({"30+":"31"}).replace("unselect",None).astype("Int64")
)
# print(df["total_floors_count"].unique())

df["unit_per_floor"]=(
    df["unit_per_floor"].replace({"more_than_8":"9"}).replace("unselect",None).astype("Int32")
)

df["extra_person_capacity"]=(
    df["extra_person_capacity"].replace({"30+":"31"}).astype("Int32")
)
# print(df["extra_person_capacity"].unique())

In [37]:
df["transformable_price"] = df["transformable_price"].astype("boolean")

df["rent_credit_transform"] = df["rent_credit_transform"].astype("boolean")

df["has_business_deed"] = df["has_business_deed"].astype("boolean")

In [ ]:
print(df["has_balcony"].unique())

object

In [50]:
df["has_balcony"] = df["has_balcony"].replace("unselect",None).replace("true",True).replace("false",False).astype("boolean")
df["has_elevator"] = df["has_elevator"].astype("boolean")
df["has_warehouse"] = df["has_warehouse"].astype("boolean")
df["has_parking"] = df["has_parking"].astype("boolean")
df["is_rebuilt"] = df["is_rebuilt"].astype("boolean")
df["has_water"] = df["has_water"].astype("boolean")
df["has_electricity"] = df["has_electricity"].astype("boolean")
df["has_gas"] = df["has_gas"].astype("boolean")
df["has_pool"] = df["has_pool"].astype("boolean")
df["has_jacuzzi"] = df["has_jacuzzi"].astype("boolean")
df["has_sauna"] = df["has_sauna"].astype("boolean")
df["has_security_guard"] = df["has_security_guard"].astype("boolean")
df["has_barbecue"] = df["has_barbecue"].astype("boolean")

In [51]:
df.select_dtypes(include=["object"]).columns

Index(['description', 'title'], dtype='object')

Convert columns to Category to Reduce file size

In [52]:
category_cols = [
    "cat2_slug",
    "cat3_slug",
    "city_slug",
    "neighborhood_slug",
    "user_type",
    "rent_mode",
    "rent_type",
    "price_mode",
    "credit_mode",
    "deed_type",
    "property_type",
    "building_direction",
    "floor_material",
    "has_restroom",
    "has_warm_water_provider",
    "has_heating_system",
    "has_cooling_system"
]
for col in category_cols:
    df[col]= df[col].astype("category")

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 60 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   cat2_slug                   1000000 non-null  category
 1   cat3_slug                   999999 non-null   category
 2   city_slug                   999998 non-null   category
 3   neighborhood_slug           437139 non-null   category
 4   created_at_month            1000000 non-null  datetime64[ns]
 5   user_type                   288882 non-null   category
 6   description                 1000000 non-null  object
 7   title                       999946 non-null   object
 8   rent_mode                   352994 non-null   category
 9   rent_value                  351322 non-null   float64
 10  rent_to_single              19 non-null       float64
 11  rent_type                   103961 non-null   category
 12  price_mode                  573606 non-null   category
 13  price_value                 568346 non-null   float64
 14  credit_mode                 352994 non-null   category
 15  credit_value                352095 non-null   float64
 16  rent_credit_transform       352985 non-null   boolean
 17  transformable_price         352894 non-null   boolean
 18  transformable_credit        352085 non-null   float64
 19  transformed_credit          72409 non-null    float64
 20  transformable_rent          351248 non-null   float64
 21  transformed_rent            72409 non-null    float64
 22  land_size                   186396 non-null   float64
 23  building_size               980394 non-null   float64
 24  deed_type                   253458 non-null   category
 25  has_business_deed           34679 non-null    boolean
 26  floor                       541748 non-null   Int64
 27  rooms_count                 845899 non-null   float64
 28  total_floors_count          304227 non-null   Int64
 29  unit_per_floor              302037 non-null   Int32
 30  has_balcony                 506188 non-null   boolean
 31  has_elevator                541749 non-null   boolean
 32  has_warehouse               728155 non-null   boolean
 33  has_parking                 728156 non-null   boolean
 34  construction_year           815828 non-null   float64
 35  is_rebuilt                  529470 non-null   boolean
 36  has_water                   33444 non-null    boolean
 37  has_warm_water_provider     379500 non-null   category
 38  has_electricity             33445 non-null    boolean
 39  has_gas                     33430 non-null    boolean
 40  has_heating_system          368969 non-null   category
 41  has_cooling_system          350619 non-null   category
 42  has_restroom                406913 non-null   category
 43  has_security_guard          31312 non-null    boolean
 44  has_barbecue                31198 non-null    boolean
 45  building_direction          323923 non-null   category
 46  has_pool                    29390 non-null    boolean
 47  has_jacuzzi                 28728 non-null    boolean
 48  has_sauna                   28479 non-null    boolean
 49  floor_material              405984 non-null   category
 50  property_type               27057 non-null    category
 51  regular_person_capacity     29870 non-null    float64
 52  extra_person_capacity       24009 non-null    Int32
 53  cost_per_extra_person       10241 non-null    float64
 54  rent_price_on_regular_days  18068 non-null    float64
 55  rent_price_on_special_days  10463 non-null    float64
 56  rent_price_at_weekends      13551 non-null    float64
 57  location_latitude           655608 non-null   float64
 58  location_longitude          655608 non-null   float64
 59  location_radius             339699 non-null   float64
dtypes: Int32(2), Int64(2), boolean(16), category(17), datetime64[ns](1), float64(20), object(2)
memory usage: 250.9+ MB

### Checking the percentage and number of missing values

In [54]:
missing = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean()*100
})

missing = missing.sort_values(
    "missing_percent",
    ascending=False
)

missing.head(60)

                            missing_count  missing_percent
rent_to_single                     999981          99.9981
cost_per_extra_person              989759          98.9759
rent_price_on_special_days         989537          98.9537
rent_price_at_weekends             986449          98.6449
rent_price_on_regular_days         981932          98.1932
extra_person_capacity              975991          97.5991
property_type                      972943          97.2943
has_sauna                          971521          97.1521
has_jacuzzi                        971272          97.1272
has_pool                           970610          97.0610
regular_person_capacity            970130          97.0130
has_barbecue                       968802          96.8802
has_security_guard                 968688          96.8688
has_gas                            966570          96.6570
has_water                          966556          96.6556
has_electricity                    966555          96.6555
has_business_deed                  965321          96.5321
transformed_credit                 927591          92.7591
transformed_rent                   927591          92.7591
rent_type                          896039          89.6039
land_size                          813604          81.3604
deed_type                          746542          74.6542
user_type                          711118          71.1118
unit_per_floor                     697963          69.7963
total_floors_count                 695773          69.5773
building_direction                 676077          67.6077
location_radius                    660301          66.0301
has_cooling_system                 649381          64.9381
transformable_rent                 648752          64.8752
rent_value                         648678          64.8678
transformable_credit               647915          64.7915
credit_value                       647905          64.7905
transformable_price                647106          64.7106
rent_credit_transform              647015          64.7015
rent_mode                          647006          64.7006
credit_mode                        647006          64.7006
has_heating_system                 631031          63.1031
has_warm_water_provider            620500          62.0500
floor_material                     594016          59.4016
has_restroom                       593087          59.3087
neighborhood_slug                  562861          56.2861
has_balcony                        493812          49.3812
is_rebuilt                         470530          47.0530
floor                              458252          45.8252
has_elevator                       458251          45.8251
price_value                        431654          43.1654
price_mode                         426394          42.6394
location_latitude                  344392          34.4392
location_longitude                 344392          34.4392
has_warehouse                      271845          27.1845
has_parking                        271844          27.1844
construction_year                  184172          18.4172
rooms_count                        154101          15.4101
building_size                       19606           1.9606
title                                  54           0.0054
city_slug                               2           0.0002
cat3_slug                               1           0.0001
description                             0           0.0000
created_at_month                        0           0.0000
cat2_slug                               0           0.0000